### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by valuta1995** [DevelopmentalOctopus/ha-buttplug#1]
I've copied over the files so that they are located ion /config/custom_components/buttplug/ (see screenshot)
![image](https://user-images.githubusercontent.com/14346905/179257627-232db92c-c006-4ea6-9591-974bda7d7797.png)

However, even after restarting the integration does not show up in HA.

**Comment by DevelopmentalOctopus** [comment]
That's unexpected; do you have any relevant logs from home-assistant? does it notice and warn about buttplug?

**Comment by DevelopmentalOctopus** [comment]
Long-term I'll want to set this up for proper HACS installation, but I was planning to test it more and improve reconnection-logic before doing that.

**Comment by DevelopmentalOctopus** [comment]
Lol I forgot to add a comma in the manifest.json file; that's almost definitely it. Uploading a version with adjusted documentation soon; and HACS support.

**Comment by valuta1995** [comment]
The only thing I got was this:
```2022-07-15 17:40:17 ERROR (SyncWorker_1) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/buttplug/manifest.json: expected `,` or `}` at line 13 column 3: line 13 column 3 (char 328)```

So yeah, you're right I think.

**Comment by DevelopmentalOctopus** [comment]
Should be fixed now; thanks for reporting the issue!
